### ISSUE TITLE
GameCube adapter misbehaving randomly

### ISSUE THREAD

**Issue by tomlube** [AxioDL/metaforce#373]
https://www.youtube.com/watch?v=0598KT_TAo4

Don't remember having this issue on macOS or linux ever, but that's also not primarily where I test

**Comment by Antidote** [comment]
This definitely needs to be fixed, and it's actually an issue on all platforms.

**Comment by tomlube** [comment]
I've not had this issue since SDL implementation so i'm going to mark it as fixed until it shows up again 😌
