### ISSUE TITLE
Omega Research door visual bug

### ISSUE THREAD

**Issue by tomlube** [AxioDL/metaforce#379]
![image](https://user-images.githubusercontent.com/4616948/112764482-bc4f0280-8fd6-11eb-85aa-047584477996.png)

**Comment by encounter** [comment]
Lighting bug, similar issue appears in Arboretum

**Comment by tomlube** [comment]
![image](https://user-images.githubusercontent.com/4616948/112765212-12717500-8fda-11eb-900f-0baf53157398.png)
yeah i was wondering about this too

**Comment by tomlube** [comment]
![image](https://user-images.githubusercontent.com/4616948/117729245-8fd2fc80-b1b8-11eb-8ec0-a750d19ce570.png)
still present actually, although arboretum is fixed

**Comment by tomlube** [comment]
![image](https://user-images.githubusercontent.com/4616948/117729815-623a8300-b1b9-11eb-81c4-b31b0140ef49.png)
also, no idea if this is related but maybe.

**Comment by Antidote** [comment]
Both of those appear to be a bug with VISI generation, the doors are actually missing, not unlit.

**Comment by tomlube** [comment]
https://youtu.be/yTtVsYWihXs

the plot thickens... notice the box too. Everything appears correctly when at a specific position

**Comment by Antidote** [comment]
Video is set to private

**Comment by tomlube** [comment]
fixed sorry lol, definitely a visigen bug

**Comment by Antidote** [comment]
Looks like our octant handling is broken somehow.

**Comment by tomlube** [comment]
![image](https://user-images.githubusercontent.com/4616948/117730705-c9a50280-b1ba-11eb-8552-1e5cd1c55d0b.png)
not sure if this is helpful, but it does at least appear correctly when the room is transitioned to Vent Shaft...

**Comment by Antidote** [comment]
I wonder if we're not setting something correctly in the constructor/PostConstruct

**Comment by tomlube** [comment]
Fixed in.... whatever commit removed VISI
