### ISSUE TITLE
some things are lit too dark

### ISSUE THREAD

**Issue by tomlube** [AxioDL/metaforce#408]
![image](https://user-images.githubusercontent.com/4616948/118013640-53baab80-b320-11eb-8b91-a63f09d84e5e.png)
![image](https://user-images.githubusercontent.com/4616948/118013701-6a610280-b320-11eb-8c97-e2880137cc20.png)
![image](https://user-images.githubusercontent.com/4616948/118013823-882e6780-b320-11eb-9b65-51cff733cffd.png)
![image](https://user-images.githubusercontent.com/4616948/118014081-d17eb700-b320-11eb-9bf4-278043086ec9.png)
regression after build commit 847211f

**Comment by encounter** [comment]
Fixed in 70b15c19a966b5c2a97ceba03a07bb7a909c661d
