### ISSUE TITLE
WorldLayer names and layer name offsets are incorrect

### ISSUE THREAD

**Issue by henriquegemignani** [AxioDL/metaforce#411]
The names are slightly wrong, while the offsets makes absolutely no sense

Here are the values extracted from 0-00 GC pak file for Tallon Overworld
[0-00 gc tallon.txt](https://github.com/AxioDL/metaforce/files/6562521/0-00.gc.tallon.txt)

These are the values that Metaforce reads:
![image](https://user-images.githubusercontent.com/884928/120023475-1cb9ea80-bfee-11eb-91cd-a066c97ee65f.png)
![image](https://user-images.githubusercontent.com/884928/120023488-20e60800-bfee-11eb-8b33-16aa5b088092.png)

**Comment by Antidote** [comment]
Is this confirmed to be fixed in the latest commit?
You'll need to recook unfortunately

**Comment by Antidote** [comment]
This is fixed with 4cd242a...d755982
