### ISSUE TITLE
MP1 Metaforce hangs at main menu (no graphics or sound) [Involves CModelShaders]

### ISSUE THREAD

**Issue by AceSoren** [AxioDL/metaforce#420]
I'll get this outta the way:
GTX 670 - AMD FX-6300 (Overclocked) - 16GB DDR3 1333 RAM

Problem: Potential CModelShaders hang, Vulkan drained at 2-5 MB left (which is probably on my end)
Expected: After logo splash, enter main menu
Happening: Main menu hangs on CModelShaders, the first thing it loads.

**Comment by Antidote** [comment]
Going to make this a low priority issue for the time being and not assign it to a milestone. Ideally it'll be resolved before Alpha 2 but we can't make any guarantees yet.
