### ISSUE TITLE
Space Pirate models are mangled in Observatory room

### ISSUE THREAD

**Issue by BoofOof32** [AxioDL/metaforce#422]
I... don't even know what to say about this. All I can say is that so far I've only seen this happen in the Observatory room, they looked fine in the prior rooms.

https://user-images.githubusercontent.com/66644514/127804485-a1d852cf-6bec-4dbe-a5dd-888ae433aba1.mp4

**Comment by encounter** [comment]
Also mentioned in #326, leaving for video
