### ISSUE TITLE
Super Missile Particle issue 

### ISSUE THREAD

**Issue by BoofOof32** [AxioDL/metaforce#423]
Very minor, but the when firing super missiles, the particles just kinda fly all over the place

https://user-images.githubusercontent.com/66644514/128242465-76234625-85fc-4485-b37b-3e04edb5ac5f.mp4

for comparison, they normally look like this

https://user-images.githubusercontent.com/66644514/128243157-a1eb92c4-12e6-46d8-878e-002f0e93ed1b.mp4

_How to reproduce_: just fire a super missile

**Comment by encounter** [comment]
Fixed by #432
