### ISSUE TITLE
Metaforce abruptly closes in Quarantine Access B room with X-Ray visor on

### ISSUE THREAD

**Issue by BoofOof32** [AxioDL/metaforce#424]
I don't know why, but everytime I make it to the Quarantine Access B room, Metaforce just hangs itself, it might have something to do with the X-Ray visor. this is currently holding me back from completion 

https://user-images.githubusercontent.com/66644514/128312254-62395d79-c6f1-4c65-9fd1-e2facc2856ea.mp4

_How to reproduce_: my best guess is to go into Quarantine Access B and switch to X-Ray Visor

**Comment by BoofOof32** [comment]
Ok, so it seems that Metaforce only crashes in this room if you have the X-ray visor turned on. Otherwise I can pass through this room

**Comment by tomlube** [comment]
I can replicate this

**Comment by Antidote** [comment]
Fixed in 3bb05c0
