### ISSUE TITLE
Cannot this project be build over the oldest supported Ubuntu LTS or Debian Stable?

### ISSUE THREAD

**Issue by EchedeyLR** [AxioDL/metaforce#426]
I have ran into an issue recently trying to run the AppImage just because only supports GLibC 2.29 while I am using Debian 10 which only have GLibC 2.28.

**Comment by Antidote** [comment]
Unfortunately we can't support anything lower than 2.29 due to features that aren't in earlier versions.

**Comment by EchedeyLR** [comment]
Is there a list of these needed features and reasons?

**Comment by encounter** [comment]
We base the AppImage on Ubuntu 20.04 because we require: GCC 9+ or Clang 10+, CMake 3.15+, Vulkan 1.1, various other dependencies. glibc 2.29 just happens to be a consequence of that, unfortunately.

**Comment by EchedeyLR** [comment]
Getting inside the issue.

Is there a feature specific of GCC 9+ or Clang 10+ that you use in the code?

**Comment by encounter** [comment]
Mainly C++20 features.

**Comment by EchedeyLR** [comment]
Thank you @encounter. I understand perfectly now.
