### ISSUE TITLE
Deep Colour

### ISSUE THREAD

**Issue by tomlube** [AxioDL/metaforce#437]
![image](https://user-images.githubusercontent.com/4616948/145126717-17da67e2-20c3-4af4-8470-6924d04585aa.png)

**Comment by Antidote** [comment]
I don't see the problem, just flip the monitor upside down *flees*

**Comment by tomlube** [comment]
it's also reversed too, you just need an elaborate system of mirrors to use it correctly

**Comment by encounter** [comment]
Deep color option is removed in `new-cmodel`.
