### ISSUE TITLE
Says I need Blender 2.93+ when I have Blender 3.0.0-4 Manjaro 

### ISSUE THREAD

**Issue by coreybruce** [AxioDL/metaforce#441]
Hi just wanted to report a bug, after extracting the game the launcher is now saying Blender is not found even tho I have 3.0.0-4, I even tried a override path to see if that would fix it but it didn't help.

I am using Manjaro x64 using the appimage

![image](https://user-images.githubusercontent.com/8393780/150682820-6affe5d2-43c7-4f1e-9e82-d601c9960b2b.png)

**Comment by Antidote** [comment]
Which build are you using?

**Comment by coreybruce** [comment]
> Which build are you using?

I was using stable

**Comment by Antidote** [comment]
use continuous and the latest version available there

**Comment by coreybruce** [comment]
> Use continuous and the latest version available there, there was an oversight that I fixed in subsequent builds.

Oh wait I did use continuous but on the application I had it set to stable

**Comment by coreybruce** [comment]
Wait why is this closed? This wasn't resolved?

**Comment by Antidote** [comment]
It was resolved, has been for a while now
