### ISSUE TITLE
Audio is broken in Pipewire 

### ISSUE THREAD

**Issue by BoofOof32** [AxioDL/metaforce#449]
https://user-images.githubusercontent.com/66644514/158537869-6d129053-7b56-44f9-a918-52cae7d336a8.mp4

Fairly self explanatory, when running Metaforce using Pipewire, audio is stuttery and incomprehensible (Also present in `New-cmodel` branch)

_How to replicate_: Just use Pipewire

**Comment by parkerlreed** [comment]
Seeing the same thing here. Changing same rate on the fly doesn't help either. 

```
pw-metadata -n settings 0 clock.force-rate 192000
```

Has more intelligible audio but still cracks

**Comment by tomlube** [comment]
> Seeing the same thing here. Changing sample rate on the fly doesn't help either.
> 
> ```
> pw-metadata -n settings 0 clock.force-rate 192000
> ```
> 
> Has more intelligible audio but still cracks

Try 96000 or maybe even 48000, 19200 is way too high a sample rate for metaforce if I recall correctly

**Comment by parkerlreed** [comment]
Yeah all of the other levels were just as clippy and more garbled.

**Comment by BoofOof32** [comment]
It seems that Audio works with no issue on Pipewire now thanks to the implementation of SDL_Audio. This change is only in `new-cmodel` though for the time being, so I'll leave this open

**Comment by Antidote** [comment]
Which branch is this? new-cmodel has a new backend wrapped around SDL's
pipewire implementation that should be better.
