### ISSUE TITLE
Manjaro Linux : Run metaforce-v0.1.3-173-linux-x86_64.AppImage

### ISSUE THREAD

**Issue by xcom169** [AxioDL/metaforce#451]
Hello All!

Why it can be that after pressing Launch just nothing happens? 
Is there any log to check it? 

https://ibb.co/HN68rGn
![image](https://user-images.githubusercontent.com/17802090/163401157-b1cf8e8b-faec-4290-a1c5-1bde64c725a4.png)

Thanks!

**Comment by Antidote** [comment]
Well, considering what's printed in that window *is* the log, unfortunately not one that's useful....
