### ISSUE TITLE
"Save Mappings" crashes program

### ISSUE THREAD

**Issue by tomlube** [AxioDL/metaforce#460]
https://www.youtube.com/watch?v=kN1Yo1KfcyY

No info given in the logs. Just exits program.

[1.5606 (62) INFO CResFactory] async-built CMDL 7D1F8126
[1.5611 (62) INFO CResFactory] async-built FRME 854EF9B3
[1.5615 (62) INFO CResFactory] async-built FRME ECD50299
PS C:\Program Files\Metaforce>

**Comment by Antidote** [comment]
Looked into this and we're already taking into account everything we need to, unless I'm missing something this isn't our bug, gotta figure out where it goes pear shaped and work around it.

**Comment by tomlube** [comment]
Fixed in [7ef204c](https://github.com/AxioDL/metaforce/commit/7ef204c552f2eca91b19ea4d1e5c3c0026a21a8f)

**Comment by Antidote** [comment]
Turns out using gnu extensions on windows tends to go very pear shaped....
