### ISSUE TITLE
Not playable on Steam Deck

### ISSUE THREAD

**Issue by The-MAZZTer** [AxioDL/metaforce#472]
I gave this a shot on my Steam Deck and had a few issues you may want to know about. I suspect it is very close to being playable with workarounds but the controller and audio not working for now kills that.

My Deck is running the latest stable SteamOS (3.5.5).

I used this version: https://releases.axiodl.com/continuous/linux/metaforce-v0.1.3-173-linux-x86_64.tar

I extracted that file to my Deck and ran it. I skipped extracting/packaging MP1 due to having difficulties with blender and ended up pushing the extraction/package files I made on my Windows machine to the Deck so I could just launch (no idea if this is supported by Metaforce but it SEEMED to work; let me know if it should make a difference or not). I added metaforce to Steam and launched it in Big Picture mode and recorded some additional problems.

Here is my list:

# Blander 2.93 requirement difficult (perhaps not possible?) to satisfy

Blender 2.93 is difficult to get on the Deck. Steam's version will only install the WINDOWS version of 2.93 if you try to install it (I think this is an oversight on Blender's part since 2.93 WAS released for Linux on Steam when it was the latest version). I expect you can download the standalone release from Blender's site but I did not get around to trying this.

Workaround:

I copied my extraction/package files from my Windows box. This seemed to work.

Possible solutions:

Might be useful if Metaforce can leverage a flatpak version, and/or if it is updated to use the latest Blender 4,0 (which does install properly on the Deck). If it is necessary to use the tool on Linux to get output suitable for Linux, I suggest adding an option to the GUI for cross-platform building, if possible. If not, consider documenting my workaround as a solution. :)

# Metaforce UI mangled when run from Steam Big Picture mode

Not sure if you can reproduce this outside of the Deck. But on the Deck, launching Metaforce via Steam in Big Picture mode (the default and recommended mode there) causes the GUI window to appear very high DPI, and the mouse can only move in the upper left quadrant.

Workaround:

I attached a hardware keyboard and tabbed to the launch button and pressed space. You can hold the STEAM button to get access to tab and space keys as well which should work without a hardware keyboard but I didn't try it.

Configuring Metaforce can be done in Desktop mode where the UI displays normally.

Possible solutions:

Probably a Steam Deck issue, perfectly valid to just say it's their problem, but you might be able to work around this somehow. It would be nice if there was a command line flag I could pass in to immediately launch and bypass the initial UI, or if there is one, if it was clearly documented in the github README.

# Audio stutters

Audio just doesn't play acceptably and has bursts of audio interspersed with silence. The framerate is 60 FPS so that's not an issue.

No ideas for workarounds or solutions. Not my area of expertise.

# Controller not working

Controller inputs from the built-in Steam Deck controller weren't processed by the game. Steam Input was sending controller inputs to Metaforce but it did not do anything. I had the Steam controller configuration for Metaforce set to the standard Gamepad with Joystick Trackpad preset.

Workaround:

I attached a hardware keyboard to navigate the menus but obviously I wasn't going to play the game like that.

---

Didn't dig much further since there wasn't much point with the controller not working.

Let me know if there would be any point in trying to run the extraction natively with blender on the Deck (since things seemed to mostly work except the audio I expect not).

Also let me know if you need any more info or want me to try anything further to help you diagnose the issue.

**Comment by Antidote** [comment]
Long time no see @The-MAZZTer, unfortunately the version you used is old and unsupported, and does not work on SteamDeck, the latest commit *does* work on SteamDeck but currently has issues building, which will be addressed really soon.
