### ISSUE TITLE
Metaforce won't work with blender 4.0 (linux)

### ISSUE THREAD

**Issue by F3arM3** [AxioDL/metaforce#473]
it can see that I have blender 4.0, but it marks it red in system check and keeps giving me this message "Blender 2.83 or greater must be installed (2.93 recommended). Please download via Steam or blender.org."

**Comment by Antidote** [comment]
Hecl is no longer in active development.

**Comment by F3arM3** [comment]
just checking if I'm reading this right, but the most recent versions of this project no longer require blender, but they are not available to the public (likely due to the big N) but they hopefully should be working soon

**Comment by BoofOof32** [comment]
@F3arM3 the most recent builds of metaforce are found in the [Actions tab](https://github.com/AxioDL/metaforce/actions). But the problem is the recent commits are failing to build on Actions CI. So downloadable binaries are currently unavailable.

**Comment by Antidote** [comment]
Nintendo has nothing to do with our builds failing, it's compiler errors and other dumb shenanigans that we're having to deal with rn.
